services:
  bajacloud:
    container_name: ucalg-baja-cloud
    image: darkicewolf50/ucalg-baja-cloud:latest
    # restart: unless-stopped
    build: . # do not include in delpoyment version
    ports:
      - 6525:6525
    environment:
      MERCH_DATABASE: /app/data/Merch.xlsx
      SPONSOR_DATABASE: /app/data/sponsorship.yaml
    volumes:
      - ./Database:./Database
