services:
  bajacloud:
    container_name: ucalg-baja-cloud
    image: darkicewolf50/ucalg-baja-cloud:latest
    # restart: unless-stopped
    build: . # do not include in delpoyment version
    ports:
      - 8000:6525
    volumes:
      - ./Database:./Database
